export { LoginService } from "./AuthServices/Login-Service";
export { SignupService } from "./AuthServices/Signup-Service";
export { EditNote } from "./NoteService/editNote";
export { AddNote } from "./NoteService/addNote";
export { GetNote } from "./NoteService/getNote";
export {ArchiveNote } from "./ArchiveNoteServices/ArchiveService";
export { UnarchiveNote } from "./ArchiveNoteServices/UnArchiveService";
export {AddTrash} from"./TrashService/AddTrash";
export {RestoreTrash} from "./TrashService/RestoreTrash";
export {DeleteTrash} from "./TrashService/DeleteTrash";
